using System.Collections.Generic;
using System.Text.Json.Serialization;
using Toggl.Api.Models;

namespace Toggl.Api;

/// <summary>
/// Source-generated JSON serializer context for .NET 10+ compatibility.
/// .NET 10 disables reflection-based JSON serialization by default.
/// </summary>
[JsonSourceGenerationOptions(
	PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
	WriteIndented = true)]

// Core models
[JsonSerializable(typeof(Activity))]
[JsonSerializable(typeof(AlphaFeature))]
[JsonSerializable(typeof(Client))]
[JsonSerializable(typeof(ClientCreationDto))]
[JsonSerializable(typeof(CsvUploadData))]
[JsonSerializable(typeof(CurrentUser))]
[JsonSerializable(typeof(CurrentUserClient))]
[JsonSerializable(typeof(Dashboard))]
[JsonSerializable(typeof(DetailedReportRequest))]
[JsonSerializable(typeof(DetailedReportTimeEntry))]
[JsonSerializable(typeof(DetailedReportTimeEntryGroup))]
[JsonSerializable(typeof(DownloadRequestRecord))]
[JsonSerializable(typeof(ExportPayload))]
[JsonSerializable(typeof(Favorite))]
[JsonSerializable(typeof(FavoriteDto))]
[JsonSerializable(typeof(Feature))]
[JsonSerializable(typeof(Group))]
[JsonSerializable(typeof(GroupCreationDto))]
[JsonSerializable(typeof(GroupPatchDto))]
[JsonSerializable(typeof(GroupUpdateDto))]
[JsonSerializable(typeof(GroupUser))]
[JsonSerializable(typeof(Invitation))]
[JsonSerializable(typeof(InvitationCreationDto))]
[JsonSerializable(typeof(InvitationResult))]
[JsonSerializable(typeof(InvoiceSummary))]
[JsonSerializable(typeof(Location))]
[JsonSerializable(typeof(MeUpdateDto))]
[JsonSerializable(typeof(MostActiveUser))]
[JsonSerializable(typeof(NewBlogPost))]
[JsonSerializable(typeof(Organization))]
[JsonSerializable(typeof(OrganizationCreationDto))]
[JsonSerializable(typeof(OrganizationOwner))]
[JsonSerializable(typeof(OrganizationUpdateDto))]
[JsonSerializable(typeof(OrganizationUser))]
[JsonSerializable(typeof(OrganizationUserUpdateDto))]
[JsonSerializable(typeof(OrganizationUsersQuery))]
[JsonSerializable(typeof(Page<ProjectTask>))]
[JsonSerializable(typeof(PaymentCard))]
[JsonSerializable(typeof(PaymentFailedInfo))]
[JsonSerializable(typeof(PaymentMethod))]
[JsonSerializable(typeof(Period))]
[JsonSerializable(typeof(PricingPlan))]
[JsonSerializable(typeof(Project))]
[JsonSerializable(typeof(ProjectCreationDto))]
[JsonSerializable(typeof(ProjectReportDashboard))]
[JsonSerializable(typeof(ProjectStatistics))]
[JsonSerializable(typeof(ProjectSummaryReportItem))]
[JsonSerializable(typeof(ProjectTask))]
[JsonSerializable(typeof(ProjectUser))]
[JsonSerializable(typeof(PushServiceToken))]
[JsonSerializable(typeof(Quota))]
[JsonSerializable(typeof(Rate))]
[JsonSerializable(typeof(RecurringParameter))]
[JsonSerializable(typeof(Report))]
[JsonSerializable(typeof(ReportRequest))]
[JsonSerializable(typeof(ReportTimeEntry))]
[JsonSerializable(typeof(Session))]
[JsonSerializable(typeof(Subscription))]
[JsonSerializable(typeof(SubscriptionCreationDto))]
[JsonSerializable(typeof(SubscriptionCustomer))]
[JsonSerializable(typeof(SubscriptionCustomerDto))]
[JsonSerializable(typeof(SubscriptionPromoCodeDto))]
[JsonSerializable(typeof(SubscriptionTrialDto))]
[JsonSerializable(typeof(Tag))]
[JsonSerializable(typeof(TagCreationDto))]
[JsonSerializable(typeof(TaskCreationDto))]
[JsonSerializable(typeof(TimeEntry))]
[JsonSerializable(typeof(TimeEntryBulkEditDto))]
[JsonSerializable(typeof(TimeEntryCreationDto))]
[JsonSerializable(typeof(TimeEntryUpdateDto))]
[JsonSerializable(typeof(Timesheet))]
[JsonSerializable(typeof(TrackReminder))]
[JsonSerializable(typeof(TrackReminderCreationDto))]
[JsonSerializable(typeof(TrialInfo))]
[JsonSerializable(typeof(User))]
[JsonSerializable(typeof(UserAdd))]
[JsonSerializable(typeof(UserEdit))]
[JsonSerializable(typeof(UserExtended))]
[JsonSerializable(typeof(UserFlags))]
[JsonSerializable(typeof(UserGroup))]
[JsonSerializable(typeof(UserPreferences))]
[JsonSerializable(typeof(UserWorkspace))]
[JsonSerializable(typeof(Workspace))]
[JsonSerializable(typeof(WorkspaceCreationDto))]
[JsonSerializable(typeof(WorkspaceFeature))]
[JsonSerializable(typeof(WorkspaceProjectReportItem))]
[JsonSerializable(typeof(WorkspaceStatistics))]
[JsonSerializable(typeof(WorkspaceUser))]
[JsonSerializable(typeof(WorkspaceUserUpdateDto))]

// Collections - these are needed for API responses that return arrays
[JsonSerializable(typeof(ICollection<Activity>))]
[JsonSerializable(typeof(ICollection<AlphaFeature>))]
[JsonSerializable(typeof(ICollection<Client>))]
[JsonSerializable(typeof(ICollection<CurrentUserClient>))]
[JsonSerializable(typeof(ICollection<DetailedReportTimeEntry>))]
[JsonSerializable(typeof(ICollection<DetailedReportTimeEntryGroup>))]
[JsonSerializable(typeof(ICollection<DownloadRequestRecord>))]
[JsonSerializable(typeof(ICollection<Favorite>))]
[JsonSerializable(typeof(ICollection<Feature>))]
[JsonSerializable(typeof(ICollection<Group>))]
[JsonSerializable(typeof(ICollection<GroupPatchDto>))]
[JsonSerializable(typeof(ICollection<GroupUser>))]
[JsonSerializable(typeof(ICollection<Invitation>))]
[JsonSerializable(typeof(ICollection<InvoiceSummary>))]
[JsonSerializable(typeof(ICollection<long>))]
[JsonSerializable(typeof(ICollection<MostActiveUser>))]
[JsonSerializable(typeof(ICollection<NewBlogPost>))]
[JsonSerializable(typeof(ICollection<Organization>))]
[JsonSerializable(typeof(ICollection<OrganizationUser>))]
[JsonSerializable(typeof(ICollection<Project>))]
[JsonSerializable(typeof(ICollection<ProjectSummaryReportItem>))]
[JsonSerializable(typeof(ICollection<ProjectTask>))]
[JsonSerializable(typeof(ICollection<ProjectUser>))]
[JsonSerializable(typeof(ICollection<RecurringParameter>))]
[JsonSerializable(typeof(ICollection<ReportTimeEntry>))]
[JsonSerializable(typeof(ICollection<string>))]
[JsonSerializable(typeof(ICollection<Subscription>))]
[JsonSerializable(typeof(ICollection<Tag>))]
[JsonSerializable(typeof(ICollection<TimeEntry>))]
[JsonSerializable(typeof(ICollection<TimeEntryBulkEditDto>))]
[JsonSerializable(typeof(ICollection<Timesheet>))]
[JsonSerializable(typeof(ICollection<TrackReminder>))]
[JsonSerializable(typeof(ICollection<User>))]
[JsonSerializable(typeof(ICollection<UserGroup>))]
[JsonSerializable(typeof(ICollection<UserWorkspace>))]
[JsonSerializable(typeof(ICollection<Workspace>))]
[JsonSerializable(typeof(ICollection<WorkspaceFeature>))]
[JsonSerializable(typeof(ICollection<WorkspaceProjectReportItem>))]
[JsonSerializable(typeof(ICollection<WorkspaceUser>))]

// Lists - some APIs may return List<T>
[JsonSerializable(typeof(List<Activity>))]
[JsonSerializable(typeof(List<Client>))]
[JsonSerializable(typeof(List<Group>))]
[JsonSerializable(typeof(List<Organization>))]
[JsonSerializable(typeof(List<OrganizationUser>))]
[JsonSerializable(typeof(List<Project>))]
[JsonSerializable(typeof(List<ProjectTask>))]
[JsonSerializable(typeof(List<ProjectUser>))]
[JsonSerializable(typeof(List<Tag>))]
[JsonSerializable(typeof(List<TimeEntry>))]
[JsonSerializable(typeof(List<User>))]
[JsonSerializable(typeof(List<Workspace>))]
[JsonSerializable(typeof(List<WorkspaceUser>))]

public partial class TogglJsonSerializerContext : JsonSerializerContext
{
}
